version: "3.8"

# For documentation see: https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose
secrets:
  pihole_web_password:
    file: ./secrets/pihole_web_password.txt

# For documentation see: https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: "Europe/Vienna"
      WEBPASSWORD_FILE: "/run/secrets/pihole_web_password"
      FTLCONF_LOCAL_IPV4: 192.168.0.250
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSSEC: "true"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      WEBTHEME: "default-dark"
      INTERFACE: "eth0"
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    network_mode: "host" # for DHCP
    cap_add:
      - NET_ADMIN # for DHCP
    restart: unless-stopped
